'use strict';
export const SET_ARTICLE_LIST = 'SET_ARTICLE_LIST';
export const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL';
export const SET_SAVE_ARTICLE = 'SET_SAVE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SET_USER_DELETE = 'SET_USER_DELETE';
export const SET_QUESTION_DELETE = 'SET_QUESTION_DELETE';